# Generated by Django 4.0.3 on 2022-03-17 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=15)),
                ('interested', models.CharField(max_length=250)),
                ('car_title', models.CharField(max_length=250)),
                ('message', models.CharField(max_length=250)),
                ('user_id', models.CharField(max_length=250)),
                ('car_id', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
