# Generated by Django 4.0.3 on 2022-03-13 06:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('photo', models.ImageField(upload_to='media/%Y/%m/%d/')),
                ('intro', ckeditor.fields.RichTextField()),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=250)),
                ('facebook_lenk', models.URLField(max_length=300)),
                ('twitter_lenk', models.URLField(max_length=300)),
                ('instagram_link', models.URLField(max_length=300)),
                ('linkedin_link', models.URLField(max_length=300)),
            ],
        ),
    ]
