# Generated by Django 4.0.3 on 2022-03-13 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_agent_phone_alter_agent_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='facebook_lenk',
            new_name='facebook_link',
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='twitter_lenk',
            new_name='twitter_link',
        ),
    ]
