# Generated by Django 4.0.3 on 2022-03-13 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_updated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='updated_date',
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
