# Generated by Django 4.0.3 on 2022-03-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_blog_updated_date_alter_blog_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='created_date_t',
            field=models.DateTimeField(auto_now_add=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='updated_date_t',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
