# Generated by Django 4.0.3 on 2022-03-14 11:50

import ckeditor.fields
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('photo', models.ImageField(upload_to='properties/%Y/%m/%d/')),
                ('photo_1', models.ImageField(upload_to='properties/%Y/%m/%d/')),
                ('price', models.IntegerField()),
                ('description', ckeditor.fields.RichTextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('AN', 'Andaman and Nicobar Islands'), ('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CH', 'Chandigarh'), ('CT', 'Chhattisgarh'), ('DN', 'Dadra and Nagar Haveli'), ('DD', 'Daman and Diu'), ('DL', 'Delhi'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himachal Pradesh'), ('JK', 'Jammu and Kashmir'), ('JH', 'Jharkhand'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('LD', 'Lakshadweep'), ('MP', 'Madhya Pradesh'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OR', 'Odisha'), ('PY', 'Puducherry'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TG', 'Telangana'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('UT', 'Uttarakhand'), ('WB', 'West Bengal')], max_length=2)),
                ('city', models.CharField(max_length=200)),
                ('property_id', models.CharField(blank=True, default='202203114172046801326', max_length=50)),
                ('status', models.CharField(choices=[('Sale', 'Sale'), ('Sold', 'Sold'), ('Rent', 'Rent')], max_length=50)),
                ('property_type', models.CharField(choices=[('House', 'House'), ('Villa', 'Villa'), ('Apartment', 'Apartment')], max_length=50)),
                ('area', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('baths', models.IntegerField()),
                ('garage', models.IntegerField()),
                ('is_featured', models.BooleanField(default=False)),
                ('amenities', multiselectfield.db.fields.MultiSelectField(choices=[('Balcony', 'Balcony'), ('Deck', 'Deck'), ('Outdoor Kitchen', 'Outdoor Kitchen'), ('Tennis Courts', 'Tennis Courts'), ('Parking', 'Parking'), ('Sun Room', 'Sun Room'), ('Cable Tv', 'Cable Tv'), ('Internet', 'Internet'), ('Concrete Flooring', 'Concrete Flooring')], max_length=95)),
            ],
        ),
    ]
